import {MigrationInterface, QueryRunner} from "typeorm";

export class includingDefaultInservicesEntity1655276778137 implements MigrationInterface {
    name = 'includingDefaultInservicesEntity1655276778137'

    public async up(queryRunner: QueryRunner): Promise<void> {
    //     await queryRunner.query("ALTER TABLE `carts` DROP FOREIGN KEY `FK_7d0e145ebd287c1565f15114a18`");
    //     await queryRunner.query("ALTER TABLE `carts` DROP FOREIGN KEY `FK_ab18eaf5265160d3dc8d70d9227`");
    //     await queryRunner.query("ALTER TABLE `generated_video_tags` DROP FOREIGN KEY `FK_3d0fba6255dd2335034e78dd25a`");
    //     await queryRunner.query("ALTER TABLE `generated_video_tags` DROP FOREIGN KEY `FK_009993ac242f5343e6b9a2b5c0c`");
    //     await queryRunner.query("ALTER TABLE `promotional_comments` DROP FOREIGN KEY `FK_8d2bd18dfbc56788fb3eb9f6460`");
    //     await queryRunner.query("ALTER TABLE `promotional_comments` DROP FOREIGN KEY `FK_f5dd43a69913c2bfae925f4bcea`");
    //     await queryRunner.query("ALTER TABLE `promotional_likes` DROP FOREIGN KEY `FK_3b40b6056b45040706bb9e09f00`");
    //     await queryRunner.query("ALTER TABLE `promotional_likes` DROP FOREIGN KEY `FK_5c28d36e7ae9177124dfd56134b`");
    //     await queryRunner.query("ALTER TABLE `shops` DROP FOREIGN KEY `FK_045cb5bc6b83e5d5f99f4a7966c`");
    //     await queryRunner.query("ALTER TABLE `peggs` DROP FOREIGN KEY `FK_b15dc25d7663ee05f6c234679c8`");
    //     await queryRunner.query("ALTER TABLE `product_videos` DROP FOREIGN KEY `FK_14c0e41e47390047c5a9c8b3cb5`");
    //     await queryRunner.query("ALTER TABLE `product_videos` DROP FOREIGN KEY `FK_4bee29aa25fc3adccf1653731df`");
    //     await queryRunner.query("ALTER TABLE `user_activities` DROP FOREIGN KEY `FK_a283f37e08edf5e37d38b375eec`");
    //     await queryRunner.query("ALTER TABLE `users` DROP FOREIGN KEY `FK_d98a275f8bc6cd986fcbe2eab01`");
    //     await queryRunner.query("ALTER TABLE `product_likes` DROP FOREIGN KEY `FK_4e72406feff8da9492589672947`");
    //     await queryRunner.query("ALTER TABLE `products` DROP FOREIGN KEY `FK_1530a6f15d3c79d1b70be98f2be`");
    //     await queryRunner.query("ALTER TABLE `products` DROP FOREIGN KEY `FK_176b502c5ebd6e72cafbd9d6f70`");
    //     await queryRunner.query("ALTER TABLE `products` DROP FOREIGN KEY `FK_3fffb0be83ac483af3a55f41170`");
    //     await queryRunner.query("ALTER TABLE `products` DROP FOREIGN KEY `FK_9a5f6868c96e0069e699f33e124`");
    //     await queryRunner.query("DROP INDEX `REL_4bee29aa25fc3adccf1653731d` ON `product_videos`");
    //     await queryRunner.query("CREATE TABLE `product_picture` (`id` varchar(36) NOT NULL, `picture` varchar(255) NOT NULL, `thumbnail` varchar(255) NOT NULL, `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `product_id` varchar(255) NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
    //     await queryRunner.query("CREATE TABLE `order_item` (`id` varchar(36) NOT NULL, `order_id` varchar(255) NOT NULL, `product_id` varchar(255) NOT NULL, `quantity` int NOT NULL, `reference` char(20) NOT NULL, `size` char(10) NOT NULL, `color` char(20) NOT NULL, `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (`id`)) ENGINE=InnoDB");
    //     await queryRunner.query("CREATE TABLE `order` (`id` varchar(36) NOT NULL, `uuid` varchar(255) NOT NULL, `reference` varchar(99) NOT NULL, `amount` decimal(10,2) NOT NULL, `name` varchar(255) NOT NULL, `note` longtext NOT NULL, `address` longtext NOT NULL, `phone` varchar(255) NOT NULL, `email` varchar(255) NOT NULL, `payment_type` varchar(255) NOT NULL, `status` int NOT NULL DEFAULT 0, `payment_status` int NOT NULL DEFAULT 1, `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (`id`)) ENGINE=InnoDB");
    //     await queryRunner.query("CREATE TABLE `token` (`id` varchar(36) NOT NULL, `email` varchar(255) NOT NULL, `token` varchar(255) NOT NULL, `uuid` varchar(255) NOT NULL, `expires_at` bigint NOT NULL, `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE INDEX `IDX_a9a66098c2fb758dff713f8d83` (`uuid`), PRIMARY KEY (`id`)) ENGINE=InnoDB");
    //     await queryRunner.query("CREATE TABLE `product_comment` (`id` varchar(36) NOT NULL, `uuid` varchar(255) NOT NULL, `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `product_id` varchar(255) NOT NULL, `comment` longtext NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
    //     await queryRunner.query("CREATE TABLE `subcategories` (`id` varchar(36) NOT NULL, `name` varchar(255) NOT NULL, `slug` varchar(255) NOT NULL, `image_url` varchar(255) NOT NULL, `description` varchar(255) NOT NULL, `category_id` varchar(255) NOT NULL, `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (`id`)) ENGINE=InnoDB");
    //     await queryRunner.query("CREATE TABLE `promotional_videos` (`id` char(91) NOT NULL, `user_id` varchar(91) NOT NULL, `product_id` longtext NULL, `title` char(91) NOT NULL, `video_url` varchar(191) NOT NULL, `mp4_url` varchar(191) NOT NULL, `video` longtext NOT NULL, `thumbnail` varchar(191) NOT NULL, `video_aspect_ratio` varchar(191) NOT NULL, `latitude` varchar(191) NULL, `longitude` varchar(191) NULL, `description` char(191) NULL, `category_id` varchar(255) NOT NULL, `sub_category_id` varchar(255) NOT NULL, `status` int NOT NULL DEFAULT 0, `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (`id`)) ENGINE=InnoDB");
    //     await queryRunner.query("CREATE TABLE `category` (`id` varchar(36) NOT NULL, `name` varchar(255) NOT NULL, `slug` varchar(255) NOT NULL, `image_url` varchar(255) NOT NULL, `description` varchar(255) NOT NULL, `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE INDEX `IDX_23c05c292c439d77b0de816b50` (`name`), PRIMARY KEY (`id`)) ENGINE=InnoDB");
    //     await queryRunner.query("CREATE TABLE `product_video_comment` (`id` varchar(36) NOT NULL, `uuid` varchar(255) NOT NULL, `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `video_id` varchar(255) NOT NULL, `comment` longtext NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
    //     await queryRunner.query("CREATE TABLE `product_video_likes` (`id` varchar(36) NOT NULL, `uuid` varchar(255) NOT NULL, `likes` int NOT NULL, `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `video_id` varchar(255) NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
    //     await queryRunner.query("CREATE TABLE `brand` (`id` varchar(36) NOT NULL, `name` varchar(255) NOT NULL, `product_id` varchar(99) NOT NULL, `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (`id`)) ENGINE=InnoDB");
    //     await queryRunner.query("CREATE TABLE `pegg` (`id` varchar(36) NOT NULL, `duration` int NOT NULL, `frame_rate` int NOT NULL, `video_id` varchar(255) NULL, `product_id` varchar(255) NULL, `label` varchar(255) NOT NULL, `confidence` varchar(255) NOT NULL, `boundingBoxHeight` varchar(255) NOT NULL, `boundingBoxWidth` varchar(255) NOT NULL, `boundingBoxTop` varchar(255) NOT NULL, `boundingBoxLeft` varchar(255) NOT NULL, `millisecond` char(10) NOT NULL, `centroid` char(20) NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
    //     await queryRunner.query("CREATE TABLE `product_videos_categories_category` (`productVideosId` varchar(36) NOT NULL, `categoryId` varchar(36) NOT NULL, INDEX `IDX_e0b4b616bf39de996dc29b7054` (`productVideosId`), INDEX `IDX_778ef644710167120f69eb5571` (`categoryId`), PRIMARY KEY (`productVideosId`, `categoryId`)) ENGINE=InnoDB");
    //     await queryRunner.query("CREATE TABLE `product_videos_subcategories_subcategories` (`productVideosId` varchar(36) NOT NULL, `subcategoriesId` varchar(36) NOT NULL, INDEX `IDX_aee71e905a465bccf1d1b50215` (`productVideosId`), INDEX `IDX_e5580fb9f26dda404a495b2019` (`subcategoriesId`), PRIMARY KEY (`productVideosId`, `subcategoriesId`)) ENGINE=InnoDB");
    //     await queryRunner.query("CREATE TABLE `users_interests` (`uuid` varchar(36) NOT NULL, `interest_id` varchar(36) NOT NULL, INDEX `IDX_a84a9353e088300f9be74b2245` (`uuid`), INDEX `IDX_70bcbd738b4195c74086caa698` (`interest_id`), PRIMARY KEY (`uuid`, `interest_id`)) ENGINE=InnoDB");
    //     await queryRunner.query("CREATE TABLE `products_categories_category` (`productsId` varchar(36) NOT NULL, `categoryId` varchar(36) NOT NULL, INDEX `IDX_472c77dfe20a4c6d4258dc8379` (`productsId`), INDEX `IDX_62254eefb150c9a51119fe1a61` (`categoryId`), PRIMARY KEY (`productsId`, `categoryId`)) ENGINE=InnoDB");
    //     await queryRunner.query("CREATE TABLE `products_subcategories_subcategories` (`productsId` varchar(36) NOT NULL, `subcategoriesId` varchar(36) NOT NULL, INDEX `IDX_016da0d1d10bf7436c948a0182` (`productsId`), INDEX `IDX_63446ee0abb6d0decfa7ac2494` (`subcategoriesId`), PRIMARY KEY (`productsId`, `subcategoriesId`)) ENGINE=InnoDB");
    //     await queryRunner.query("ALTER TABLE `interests` DROP COLUMN `slug`");
    //     await queryRunner.query("ALTER TABLE `interests` DROP COLUMN `is_deleted`");
    //     await queryRunner.query("ALTER TABLE `colors` DROP COLUMN `is_deleted`");
    //     await queryRunner.query("ALTER TABLE `carts` DROP COLUMN `is_deleted`");
    //     await queryRunner.query("ALTER TABLE `promotional_comments` DROP COLUMN `is_deleted`");
    //     await queryRunner.query("ALTER TABLE `promotional_comments` DROP COLUMN `status`");
    //     await queryRunner.query("ALTER TABLE `promotional_likes` DROP COLUMN `is_deleted`");
    //     await queryRunner.query("ALTER TABLE `promotional_likes` DROP COLUMN `status`");
    //     await queryRunner.query("ALTER TABLE `shops` DROP COLUMN `logistic_id`");
    //     await queryRunner.query("ALTER TABLE `peggs` DROP COLUMN `created_at`");
    //     await queryRunner.query("ALTER TABLE `peggs` DROP COLUMN `updated_at`");
    //     await queryRunner.query("ALTER TABLE `product_videos` DROP COLUMN `user_id`");
    //     await queryRunner.query("ALTER TABLE `product_videos` DROP COLUMN `product_id`");
    //     await queryRunner.query("ALTER TABLE `product_videos` DROP COLUMN `is_deleted`");
    //     await queryRunner.query("ALTER TABLE `product_videos` DROP COLUMN `status`");
    //     await queryRunner.query("ALTER TABLE `user_activities` DROP COLUMN `is_deleted`");
    //     await queryRunner.query("ALTER TABLE `users` DROP COLUMN `address`");
    //     await queryRunner.query("ALTER TABLE `users` DROP COLUMN `is_verified`");
    //     await queryRunner.query("ALTER TABLE `users` DROP COLUMN `account_type_id`");
    //     await queryRunner.query("ALTER TABLE `users` DROP COLUMN `is_deleted`");
    //     await queryRunner.query("ALTER TABLE `users` DROP COLUMN `date_deleted`");
    //     await queryRunner.query("ALTER TABLE `product_likes` DROP COLUMN `user_id`");
    //     await queryRunner.query("ALTER TABLE `product_likes` DROP COLUMN `status`");
    //     await queryRunner.query("ALTER TABLE `products` DROP COLUMN `user_id`");
    //     await queryRunner.query("ALTER TABLE `products` DROP COLUMN `color_id`");
    //     await queryRunner.query("ALTER TABLE `products` DROP COLUMN `is_deleted`");
    //     await queryRunner.query("ALTER TABLE `products` DROP COLUMN `products_status`");
    //     await queryRunner.query("ALTER TABLE `products` DROP COLUMN `category_id`");
    //     await queryRunner.query("ALTER TABLE `products` DROP COLUMN `sub_categories_id`");
    //     await queryRunner.query("ALTER TABLE `products` DROP COLUMN `sub_category_id`");
    //     await queryRunner.query("ALTER TABLE `products` DROP COLUMN `availability`");
    //     await queryRunner.query("ALTER TABLE `otp_verifies` DROP COLUMN `user_id`");
    //     await queryRunner.query("ALTER TABLE `otp_verifies` DROP COLUMN `status`");
    //     await queryRunner.query("ALTER TABLE `activity_types` ADD `id` varchar(36) NOT NULL PRIMARY KEY");
    //     await queryRunner.query("ALTER TABLE `product_videos` ADD `uuid` varchar(255) NOT NULL");
    //     await queryRunner.query("ALTER TABLE `users` ADD `uuid` varchar(255) NOT NULL");
    //     await queryRunner.query("ALTER TABLE `users` DROP PRIMARY KEY");
    //     await queryRunner.query("ALTER TABLE `users` ADD PRIMARY KEY (`id`, `uuid`)");
    //     await queryRunner.query("ALTER TABLE `users` ADD `account_type` varchar(255) NULL");
    //     await queryRunner.query("ALTER TABLE `product_likes` ADD `uuid` varchar(255) NOT NULL");
    //     await queryRunner.query("ALTER TABLE `products` ADD `uuid` varchar(255) NOT NULL");
    //     await queryRunner.query("ALTER TABLE `products` ADD `color` text NOT NULL");
    //     await queryRunner.query("ALTER TABLE `products` ADD `size` text NOT NULL");
    //     await queryRunner.query("ALTER TABLE `products` ADD `weight` text NOT NULL");
    //     await queryRunner.query("ALTER TABLE `otp_verifies` ADD `uuid` varchar(255) NOT NULL");
    //     await queryRunner.query("DROP INDEX `IDX_616348777087f88bb8cb743e60` ON `interests`");
    //     await queryRunner.query("ALTER TABLE `interests` DROP COLUMN `name`");
    //     await queryRunner.query("ALTER TABLE `interests` ADD `name` varchar(255) NOT NULL");
    //     await queryRunner.query("ALTER TABLE `interests` ADD UNIQUE INDEX `IDX_616348777087f88bb8cb743e60` (`name`)");
    //     await queryRunner.query("ALTER TABLE `interests` DROP COLUMN `video`");
    //     await queryRunner.query("ALTER TABLE `interests` ADD `video` varchar(255) NOT NULL");
    //     await queryRunner.query("ALTER TABLE `interests` DROP COLUMN `picture`");
    //     await queryRunner.query("ALTER TABLE `interests` ADD `picture` varchar(255) NOT NULL");
    //     await queryRunner.query("ALTER TABLE `interests` DROP COLUMN `created_at`");
    //     await queryRunner.query("ALTER TABLE `interests` ADD `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
    //     await queryRunner.query("ALTER TABLE `interests` DROP COLUMN `updated_at`");
    //     await queryRunner.query("ALTER TABLE `interests` ADD `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
    //     await queryRunner.query("ALTER TABLE `colors` DROP COLUMN `name`");
    //     await queryRunner.query("ALTER TABLE `colors` ADD `name` varchar(255) NOT NULL");
    //     await queryRunner.query("ALTER TABLE `colors` DROP COLUMN `code`");
    //     await queryRunner.query("ALTER TABLE `colors` ADD `code` varchar(255) NOT NULL");
    //     await queryRunner.query("ALTER TABLE `colors` DROP COLUMN `created_at`");
    //     await queryRunner.query("ALTER TABLE `colors` ADD `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
    //     await queryRunner.query("ALTER TABLE `colors` DROP COLUMN `updated_at`");
    //     await queryRunner.query("ALTER TABLE `colors` ADD `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
    //     await queryRunner.query("ALTER TABLE `carts` DROP FOREIGN KEY `FK_2ec1c94a977b940d85a4f498aea`");
    //     await queryRunner.query("ALTER TABLE `carts` DROP COLUMN `user_id`");
    //     await queryRunner.query("ALTER TABLE `carts` ADD `user_id` varchar(255) NOT NULL");
    //     await queryRunner.query("ALTER TABLE `carts` DROP COLUMN `product_id`");
    //     await queryRunner.query("ALTER TABLE `carts` ADD `product_id` varchar(255) NOT NULL");
    //     await queryRunner.query("ALTER TABLE `carts` CHANGE `status` `status` int NOT NULL DEFAULT 0");
    //     await queryRunner.query("ALTER TABLE `carts` DROP COLUMN `size`");
    //     await queryRunner.query("ALTER TABLE `carts` ADD `size` varchar(255) NOT NULL");
    //     await queryRunner.query("ALTER TABLE `carts` DROP COLUMN `weight`");
    //     await queryRunner.query("ALTER TABLE `carts` ADD `weight` varchar(255) NULL");
    //     await queryRunner.query("ALTER TABLE `carts` CHANGE `quantity` `quantity` int NOT NULL");
    //     await queryRunner.query("ALTER TABLE `carts` DROP COLUMN `color_id`");
    //     await queryRunner.query("ALTER TABLE `carts` ADD `color_id` varchar(255) NOT NULL");
    //     await queryRunner.query("ALTER TABLE `carts` DROP COLUMN `created_at`");
    //     await queryRunner.query("ALTER TABLE `carts` ADD `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
    //     await queryRunner.query("ALTER TABLE `carts` DROP COLUMN `updated_at`");
    //     await queryRunner.query("ALTER TABLE `carts` ADD `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
    //     await queryRunner.query("ALTER TABLE `generated_video_tags` DROP COLUMN `video_id`");
    //     await queryRunner.query("ALTER TABLE `generated_video_tags` ADD `video_id` char(91) NOT NULL");
    //     await queryRunner.query("ALTER TABLE `generated_video_tags` DROP COLUMN `label`");
    //     await queryRunner.query("ALTER TABLE `generated_video_tags` ADD `label` varchar(255) NOT NULL");
    //     await queryRunner.query("ALTER TABLE `generated_video_tags` DROP COLUMN `price`");
    //     await queryRunner.query("ALTER TABLE `generated_video_tags` ADD `price` varchar(255) NOT NULL");
    //     await queryRunner.query("ALTER TABLE `generated_video_tags` DROP COLUMN `product_id`");
    //     await queryRunner.query("ALTER TABLE `generated_video_tags` ADD `product_id` varchar(255) NOT NULL");
    //     await queryRunner.query("ALTER TABLE `generated_video_tags` DROP COLUMN `x`");
    //     await queryRunner.query("ALTER TABLE `generated_video_tags` ADD `x` char(91) NOT NULL");
    //     await queryRunner.query("ALTER TABLE `generated_video_tags` DROP COLUMN `y`");
    //     await queryRunner.query("ALTER TABLE `generated_video_tags` ADD `y` char(91) NOT NULL");
    //     await queryRunner.query("ALTER TABLE `generated_video_tags` DROP COLUMN `created_at`");
    //     await queryRunner.query("ALTER TABLE `generated_video_tags` ADD `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
    //     await queryRunner.query("ALTER TABLE `generated_video_tags` DROP COLUMN `updated_at`");
    //     await queryRunner.query("ALTER TABLE `generated_video_tags` ADD `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
    //     await queryRunner.query("ALTER TABLE `promotional_comments` DROP PRIMARY KEY");
    //     await queryRunner.query("ALTER TABLE `promotional_comments` DROP COLUMN `id`");
    //     await queryRunner.query("ALTER TABLE `promotional_comments` ADD `id` char(91) NOT NULL PRIMARY KEY");
    //     await queryRunner.query("ALTER TABLE `promotional_comments` DROP COLUMN `user_id`");
    //     await queryRunner.query("ALTER TABLE `promotional_comments` ADD `user_id` varchar(91) NOT NULL");
    //     await queryRunner.query("ALTER TABLE `promotional_comments` DROP COLUMN `pro_vid_id`");
    //     await queryRunner.query("ALTER TABLE `promotional_comments` ADD `pro_vid_id` char(91) NOT NULL");
    //     await queryRunner.query("ALTER TABLE `promotional_comments` DROP COLUMN `created_at`");
    //     await queryRunner.query("ALTER TABLE `promotional_comments` ADD `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
    //     await queryRunner.query("ALTER TABLE `promotional_comments` DROP COLUMN `updated_at`");
    //     await queryRunner.query("ALTER TABLE `promotional_comments` ADD `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
    //     await queryRunner.query("ALTER TABLE `promotional_likes` DROP PRIMARY KEY");
    //     await queryRunner.query("ALTER TABLE `promotional_likes` DROP COLUMN `id`");
    //     await queryRunner.query("ALTER TABLE `promotional_likes` ADD `id` int NOT NULL PRIMARY KEY AUTO_INCREMENT");
    //     await queryRunner.query("ALTER TABLE `promotional_likes` DROP COLUMN `user_id`");
    //     await queryRunner.query("ALTER TABLE `promotional_likes` ADD `user_id` varchar(91) NOT NULL");
    //     await queryRunner.query("ALTER TABLE `promotional_likes` DROP COLUMN `prod_vid_id`");
    //     await queryRunner.query("ALTER TABLE `promotional_likes` ADD `prod_vid_id` char(91) NOT NULL");
    //     await queryRunner.query("ALTER TABLE `promotional_likes` DROP COLUMN `created_at`");
    //     await queryRunner.query("ALTER TABLE `promotional_likes` ADD `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
    //     await queryRunner.query("ALTER TABLE `promotional_likes` DROP COLUMN `updated_at`");
    //     await queryRunner.query("ALTER TABLE `promotional_likes` ADD `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
    //     await queryRunner.query("ALTER TABLE `shops` DROP FOREIGN KEY `FK_bb9c758dcc60137e56f6fee72f7`");
    //     await queryRunner.query("ALTER TABLE `shops` CHANGE `user_id` `user_id` varchar(191) NOT NULL");
    //     await queryRunner.query("ALTER TABLE `peggs` DROP FOREIGN KEY `FK_02056a85e905642f887f5ca99a6`");
    //     await queryRunner.query("ALTER TABLE `peggs` DROP COLUMN `video_id`");
    //     await queryRunner.query("ALTER TABLE `peggs` ADD `video_id` varchar(255) NULL");
    //     await queryRunner.query("ALTER TABLE `peggs` DROP COLUMN `product_id`");
    //     await queryRunner.query("ALTER TABLE `peggs` ADD `product_id` varchar(255) NULL");
    //     await queryRunner.query("ALTER TABLE `peggs` DROP COLUMN `label`");
    //     await queryRunner.query("ALTER TABLE `peggs` ADD `label` varchar(255) NOT NULL");
    //     await queryRunner.query("ALTER TABLE `peggs` DROP COLUMN `confidence`");
    //     await queryRunner.query("ALTER TABLE `peggs` ADD `confidence` varchar(255) NOT NULL");
    //     await queryRunner.query("ALTER TABLE `peggs` DROP COLUMN `boundingBoxHeight`");
    //     await queryRunner.query("ALTER TABLE `peggs` ADD `boundingBoxHeight` varchar(255) NOT NULL");
    //     await queryRunner.query("ALTER TABLE `peggs` DROP COLUMN `boundingBoxWidth`");
    //     await queryRunner.query("ALTER TABLE `peggs` ADD `boundingBoxWidth` varchar(255) NOT NULL");
    //     await queryRunner.query("ALTER TABLE `peggs` DROP COLUMN `boundingBoxTop`");
    //     await queryRunner.query("ALTER TABLE `peggs` ADD `boundingBoxTop` varchar(255) NOT NULL");
    //     await queryRunner.query("ALTER TABLE `peggs` DROP COLUMN `boundingBoxLeft`");
    //     await queryRunner.query("ALTER TABLE `peggs` ADD `boundingBoxLeft` varchar(255) NOT NULL");
    //     await queryRunner.query("ALTER TABLE `peggs` DROP COLUMN `millisecond`");
    //     await queryRunner.query("ALTER TABLE `peggs` ADD `millisecond` char(10) NOT NULL");
    //     await queryRunner.query("ALTER TABLE `peggs` DROP COLUMN `centroid`");
    //     await queryRunner.query("ALTER TABLE `peggs` ADD `centroid` char(20) NOT NULL");
    //     await queryRunner.query("ALTER TABLE `product_videos` DROP COLUMN `title`");
    //     await queryRunner.query("ALTER TABLE `product_videos` ADD `title` varchar(255) NOT NULL");
    //     await queryRunner.query("ALTER TABLE `product_videos` DROP COLUMN `description`");
    //     await queryRunner.query("ALTER TABLE `product_videos` ADD `description` varchar(255) NOT NULL");
    //     await queryRunner.query("ALTER TABLE `product_videos` DROP COLUMN `thumbnail`");
    //     await queryRunner.query("ALTER TABLE `product_videos` ADD `thumbnail` varchar(255) NOT NULL");
    //     await queryRunner.query("ALTER TABLE `product_videos` DROP COLUMN `json`");
    //     await queryRunner.query("ALTER TABLE `product_videos` ADD `json` varchar(255) NOT NULL");
    //     await queryRunner.query("ALTER TABLE `product_videos` DROP COLUMN `mp4_url`");
    //     await queryRunner.query("ALTER TABLE `product_videos` ADD `mp4_url` varchar(255) NULL");
    //     await queryRunner.query("ALTER TABLE `product_videos` DROP COLUMN `created_at`");
    //     await queryRunner.query("ALTER TABLE `product_videos` ADD `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
    //     await queryRunner.query("ALTER TABLE `product_videos` DROP COLUMN `updated_at`");
    //     await queryRunner.query("ALTER TABLE `product_videos` ADD `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
    //     await queryRunner.query("ALTER TABLE `user_activities` DROP PRIMARY KEY");
    //     await queryRunner.query("ALTER TABLE `user_activities` DROP COLUMN `id`");
    //     await queryRunner.query("ALTER TABLE `user_activities` ADD `id` int NOT NULL PRIMARY KEY AUTO_INCREMENT");
    //     await queryRunner.query("ALTER TABLE `user_activities` DROP COLUMN `type`");
    //     await queryRunner.query("ALTER TABLE `user_activities` ADD `type` varchar(191) NOT NULL");
    //     await queryRunner.query("ALTER TABLE `user_activities` DROP COLUMN `created_at`");
    //     await queryRunner.query("ALTER TABLE `user_activities` ADD `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
    //     await queryRunner.query("ALTER TABLE `user_activities` DROP COLUMN `updated_at`");
    //     await queryRunner.query("ALTER TABLE `user_activities` ADD `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `services` CHANGE `is_deleted` `is_deleted` tinyint NOT NULL DEFAULT 0");
    //     await queryRunner.query("ALTER TABLE `users` DROP PRIMARY KEY");
    //     await queryRunner.query("ALTER TABLE `users` ADD PRIMARY KEY (`uuid`)");
    //     await queryRunner.query("ALTER TABLE `users` DROP COLUMN `id`");
    //     await queryRunner.query("ALTER TABLE `users` ADD `id` varchar(36) NOT NULL");
    //     await queryRunner.query("DROP INDEX `IDX_fe0bb3f6520ee0469504521e71` ON `users`");
    //     await queryRunner.query("ALTER TABLE `users` DROP COLUMN `username`");
    //     await queryRunner.query("ALTER TABLE `users` ADD `username` varchar(50) NULL");
    //     await queryRunner.query("ALTER TABLE `users` ADD UNIQUE INDEX `IDX_fe0bb3f6520ee0469504521e71` (`username`)");
    //     await queryRunner.query("DROP INDEX `IDX_97672ac88f789774dd47f7c8be` ON `users`");
    //     await queryRunner.query("ALTER TABLE `users` DROP COLUMN `email`");
    //     await queryRunner.query("ALTER TABLE `users` ADD `email` varchar(255) NULL");
    //     await queryRunner.query("ALTER TABLE `users` ADD UNIQUE INDEX `IDX_97672ac88f789774dd47f7c8be` (`email`)");
    //     await queryRunner.query("ALTER TABLE `users` DROP COLUMN `phone`");
    //     await queryRunner.query("ALTER TABLE `users` ADD `phone` varchar(255) NULL");
    //     await queryRunner.query("ALTER TABLE `users` DROP COLUMN `picture`");
    //     await queryRunner.query("ALTER TABLE `users` ADD `picture` varchar(50) NOT NULL");
    //     await queryRunner.query("ALTER TABLE `users` CHANGE `gender` `gender` enum ('Unspecified', 'Male', 'Female', 'Other') NOT NULL DEFAULT 'Unspecified'");
    //     await queryRunner.query("ALTER TABLE `users` DROP COLUMN `latitude`");
    //     await queryRunner.query("ALTER TABLE `users` ADD `latitude` double NULL");
    //     await queryRunner.query("ALTER TABLE `users` DROP COLUMN `longitude`");
    //     await queryRunner.query("ALTER TABLE `users` ADD `longitude` double NULL");
    //     await queryRunner.query("ALTER TABLE `users` DROP COLUMN `device_id`");
    //     await queryRunner.query("ALTER TABLE `users` ADD `device_id` varchar(255) NULL");
    //     await queryRunner.query("ALTER TABLE `users` DROP COLUMN `device_type`");
    //     await queryRunner.query("ALTER TABLE `users` ADD `device_type` varchar(255) NULL");
    //     await queryRunner.query("ALTER TABLE `users` DROP COLUMN `country_id`");
    //     await queryRunner.query("ALTER TABLE `users` ADD `country_id` varchar(255) NULL");
    //     await queryRunner.query("ALTER TABLE `users` DROP COLUMN `country_code`");
    //     await queryRunner.query("ALTER TABLE `users` ADD `country_code` varchar(255) NULL");
    //     await queryRunner.query("ALTER TABLE `users` DROP COLUMN `password`");
    //     await queryRunner.query("ALTER TABLE `users` ADD `password` varchar(255) NULL");
    //     await queryRunner.query("ALTER TABLE `users` DROP COLUMN `email_verified_at`");
    //     await queryRunner.query("ALTER TABLE `users` ADD `email_verified_at` datetime NULL");
    //     await queryRunner.query("ALTER TABLE `users` DROP COLUMN `is_active`");
    //     await queryRunner.query("ALTER TABLE `users` ADD `is_active` varchar(255) NULL");
    //     await queryRunner.query("ALTER TABLE `users` DROP COLUMN `is_banned`");
    //     await queryRunner.query("ALTER TABLE `users` ADD `is_banned` varchar(255) NULL");
    //     await queryRunner.query("ALTER TABLE `users` DROP COLUMN `remember_token`");
    //     await queryRunner.query("ALTER TABLE `users` ADD `remember_token` varchar(255) NULL");
    //     await queryRunner.query("ALTER TABLE `users` DROP COLUMN `created_at`");
    //     await queryRunner.query("ALTER TABLE `users` ADD `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
    //     await queryRunner.query("ALTER TABLE `users` DROP COLUMN `updated_at`");
    //     await queryRunner.query("ALTER TABLE `users` ADD `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
    //     await queryRunner.query("ALTER TABLE `product_likes` DROP FOREIGN KEY `FK_7add69eb9dff06d1b36ce5fccdf`");
    //     await queryRunner.query("ALTER TABLE `product_likes` CHANGE `likes` `likes` int NOT NULL");
    //     await queryRunner.query("ALTER TABLE `product_likes` DROP COLUMN `created_at`");
    //     await queryRunner.query("ALTER TABLE `product_likes` ADD `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
    //     await queryRunner.query("ALTER TABLE `product_likes` DROP COLUMN `updated_at`");
    //     await queryRunner.query("ALTER TABLE `product_likes` ADD `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
    //     await queryRunner.query("ALTER TABLE `product_likes` DROP COLUMN `product_id`");
    //     await queryRunner.query("ALTER TABLE `product_likes` ADD `product_id` varchar(255) NOT NULL");
    //     await queryRunner.query("ALTER TABLE `products` DROP COLUMN `name`");
    //     await queryRunner.query("ALTER TABLE `products` ADD `name` varchar(255) NOT NULL");
    //     await queryRunner.query("ALTER TABLE `products` DROP COLUMN `slug`");
    //     await queryRunner.query("ALTER TABLE `products` ADD `slug` varchar(99) NOT NULL");
    //     await queryRunner.query("ALTER TABLE `products` DROP COLUMN `thumbnail`");
    //     await queryRunner.query("ALTER TABLE `products` ADD `thumbnail` varchar(99) NULL");
    //     await queryRunner.query("ALTER TABLE `products` DROP COLUMN `price`");
    //     await queryRunner.query("ALTER TABLE `products` ADD `price` double NOT NULL");
    //     await queryRunner.query("ALTER TABLE `products` CHANGE `product_processed_status` `product_processed_status` int NOT NULL");
    //     await queryRunner.query("ALTER TABLE `products` CHANGE `product_processed_meta` `product_processed_meta` longtext NOT NULL");
    //     await queryRunner.query("ALTER TABLE `products` CHANGE `description` `description` longtext NOT NULL");
    //     await queryRunner.query("ALTER TABLE `products` DROP COLUMN `brand_id`");
    //     await queryRunner.query("ALTER TABLE `products` ADD `brand_id` varchar(255) NOT NULL");
    //     await queryRunner.query("ALTER TABLE `products` CHANGE `status` `status` int NULL");
    //     await queryRunner.query("ALTER TABLE `products` CHANGE `product_status` `product_status` int NULL");
    //     await queryRunner.query("ALTER TABLE `products` DROP COLUMN `created_at`");
    //     await queryRunner.query("ALTER TABLE `products` ADD `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
    //     await queryRunner.query("ALTER TABLE `products` DROP COLUMN `updated_at`");
    //     await queryRunner.query("ALTER TABLE `products` ADD `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
    //     await queryRunner.query("DROP INDEX `IDX_f71c5348cfeceeade91fd6231e` ON `otp_verifies`");
    //     await queryRunner.query("ALTER TABLE `otp_verifies` DROP COLUMN `email`");
    //     await queryRunner.query("ALTER TABLE `otp_verifies` ADD `email` varchar(255) NULL");
    //     await queryRunner.query("ALTER TABLE `otp_verifies` ADD UNIQUE INDEX `IDX_f71c5348cfeceeade91fd6231e` (`email`)");
    //     await queryRunner.query("ALTER TABLE `otp_verifies` DROP COLUMN `created_at`");
    //     await queryRunner.query("ALTER TABLE `otp_verifies` ADD `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
    //     await queryRunner.query("ALTER TABLE `otp_verifies` DROP COLUMN `updated_at`");
    //     await queryRunner.query("ALTER TABLE `otp_verifies` ADD `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
    //     await queryRunner.query("ALTER TABLE `product_picture` ADD CONSTRAINT `FK_d4fc8e8168628ebd69131ff21dd` FOREIGN KEY (`product_id`) REFERENCES `products`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
    //     await queryRunner.query("ALTER TABLE `order_item` ADD CONSTRAINT `FK_e9674a6053adbaa1057848cddfa` FOREIGN KEY (`order_id`) REFERENCES `order`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
    //     await queryRunner.query("ALTER TABLE `order_item` ADD CONSTRAINT `FK_5e17c017aa3f5164cb2da5b1c6b` FOREIGN KEY (`product_id`) REFERENCES `products`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
    //     await queryRunner.query("ALTER TABLE `order` ADD CONSTRAINT `FK_ba94d4066f76b66d3fe0b94c283` FOREIGN KEY (`uuid`) REFERENCES `users`(`uuid`) ON DELETE NO ACTION ON UPDATE NO ACTION");
    //     await queryRunner.query("ALTER TABLE `product_comment` ADD CONSTRAINT `FK_add4013879e5a3bd0d59b9cba2e` FOREIGN KEY (`uuid`) REFERENCES `users`(`uuid`) ON DELETE CASCADE ON UPDATE NO ACTION");
    //     await queryRunner.query("ALTER TABLE `product_comment` ADD CONSTRAINT `FK_082d130dfa3d29fc2dd46141936` FOREIGN KEY (`product_id`) REFERENCES `products`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
    //     await queryRunner.query("ALTER TABLE `carts` ADD CONSTRAINT `FK_ab18eaf5265160d3dc8d70d9227` FOREIGN KEY (`color_id`) REFERENCES `colors`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
    //     await queryRunner.query("ALTER TABLE `carts` ADD CONSTRAINT `FK_7d0e145ebd287c1565f15114a18` FOREIGN KEY (`product_id`) REFERENCES `products`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
    //     await queryRunner.query("ALTER TABLE `carts` ADD CONSTRAINT `FK_2ec1c94a977b940d85a4f498aea` FOREIGN KEY (`user_id`) REFERENCES `users`(`uuid`) ON DELETE CASCADE ON UPDATE NO ACTION");
    //     await queryRunner.query("ALTER TABLE `generated_video_tags` ADD CONSTRAINT `FK_3d0fba6255dd2335034e78dd25a` FOREIGN KEY (`video_id`) REFERENCES `promotional_videos`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
    //     await queryRunner.query("ALTER TABLE `generated_video_tags` ADD CONSTRAINT `FK_009993ac242f5343e6b9a2b5c0c` FOREIGN KEY (`product_id`) REFERENCES `products`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
    //     await queryRunner.query("ALTER TABLE `promotional_comments` ADD CONSTRAINT `FK_8d2bd18dfbc56788fb3eb9f6460` FOREIGN KEY (`user_id`) REFERENCES `users`(`uuid`) ON DELETE NO ACTION ON UPDATE NO ACTION");
    //     await queryRunner.query("ALTER TABLE `promotional_comments` ADD CONSTRAINT `FK_f5dd43a69913c2bfae925f4bcea` FOREIGN KEY (`pro_vid_id`) REFERENCES `promotional_videos`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
    //     await queryRunner.query("ALTER TABLE `promotional_likes` ADD CONSTRAINT `FK_3b40b6056b45040706bb9e09f00` FOREIGN KEY (`user_id`) REFERENCES `users`(`uuid`) ON DELETE NO ACTION ON UPDATE NO ACTION");
    //     await queryRunner.query("ALTER TABLE `promotional_likes` ADD CONSTRAINT `FK_5c28d36e7ae9177124dfd56134b` FOREIGN KEY (`prod_vid_id`) REFERENCES `promotional_videos`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
    //     await queryRunner.query("ALTER TABLE `subcategories` ADD CONSTRAINT `FK_f7b015bc580ae5179ba5a4f42ec` FOREIGN KEY (`category_id`) REFERENCES `category`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
    //     await queryRunner.query("ALTER TABLE `promotional_videos` ADD CONSTRAINT `FK_f470cfd5581b2d6970cb5835346` FOREIGN KEY (`user_id`) REFERENCES `users`(`uuid`) ON DELETE NO ACTION ON UPDATE NO ACTION");
    //     await queryRunner.query("ALTER TABLE `promotional_videos` ADD CONSTRAINT `FK_201b844b99b0a5777d68581c8ce` FOREIGN KEY (`category_id`) REFERENCES `category`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
    //     await queryRunner.query("ALTER TABLE `promotional_videos` ADD CONSTRAINT `FK_cad94a0d1cc1263de58b6aa9b76` FOREIGN KEY (`sub_category_id`) REFERENCES `subcategories`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
    //     await queryRunner.query("ALTER TABLE `shops` ADD CONSTRAINT `FK_bb9c758dcc60137e56f6fee72f7` FOREIGN KEY (`user_id`) REFERENCES `users`(`uuid`) ON DELETE CASCADE ON UPDATE NO ACTION");
    //     await queryRunner.query("ALTER TABLE `shops` ADD CONSTRAINT `FK_045cb5bc6b83e5d5f99f4a7966c` FOREIGN KEY (`category_id`) REFERENCES `category`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
    //     await queryRunner.query("ALTER TABLE `peggs` ADD CONSTRAINT `FK_02056a85e905642f887f5ca99a6` FOREIGN KEY (`video_id`) REFERENCES `product_videos`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
    //     await queryRunner.query("ALTER TABLE `peggs` ADD CONSTRAINT `FK_b15dc25d7663ee05f6c234679c8` FOREIGN KEY (`product_id`) REFERENCES `products`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
    //     await queryRunner.query("ALTER TABLE `product_video_comment` ADD CONSTRAINT `FK_25bba93110aa8bd1a0dfefc9821` FOREIGN KEY (`uuid`) REFERENCES `users`(`uuid`) ON DELETE CASCADE ON UPDATE NO ACTION");
    //     await queryRunner.query("ALTER TABLE `product_video_comment` ADD CONSTRAINT `FK_1b40bb3804949aabd9eac604a2b` FOREIGN KEY (`video_id`) REFERENCES `product_videos`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
    //     await queryRunner.query("ALTER TABLE `product_video_meta` ADD CONSTRAINT `FK_fc9de53de4f59d06b8ec2346f51` FOREIGN KEY (`productvideo_id`) REFERENCES `product_videos`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
    //     await queryRunner.query("ALTER TABLE `product_videos` ADD CONSTRAINT `FK_ac5dbef0a796bca08eded59df73` FOREIGN KEY (`uuid`) REFERENCES `users`(`uuid`) ON DELETE NO ACTION ON UPDATE NO ACTION");
    //     await queryRunner.query("ALTER TABLE `product_video_likes` ADD CONSTRAINT `FK_ee327d2dc279475e612f40e2163` FOREIGN KEY (`uuid`) REFERENCES `users`(`uuid`) ON DELETE CASCADE ON UPDATE NO ACTION");
    //     await queryRunner.query("ALTER TABLE `product_video_likes` ADD CONSTRAINT `FK_1c2afb95868c0c0329864b303bb` FOREIGN KEY (`video_id`) REFERENCES `product_videos`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
    //     await queryRunner.query("ALTER TABLE `user_activities` ADD CONSTRAINT `FK_a283f37e08edf5e37d38b375eec` FOREIGN KEY (`user_id`) REFERENCES `users`(`uuid`) ON DELETE NO ACTION ON UPDATE NO ACTION");
    //     await queryRunner.query("ALTER TABLE `services` ADD CONSTRAINT `FK_421b94f0ef1cdb407654e67c59e` FOREIGN KEY (`user_id`) REFERENCES `users`(`uuid`) ON DELETE NO ACTION ON UPDATE NO ACTION");
    //     await queryRunner.query("ALTER TABLE `users` ADD CONSTRAINT `FK_d98a275f8bc6cd986fcbe2eab01` FOREIGN KEY (`tokenId`) REFERENCES `token`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
    //     await queryRunner.query("ALTER TABLE `product_likes` ADD CONSTRAINT `FK_e7dbd6e2295d469fc765a986f15` FOREIGN KEY (`uuid`) REFERENCES `users`(`uuid`) ON DELETE CASCADE ON UPDATE NO ACTION");
    //     await queryRunner.query("ALTER TABLE `product_likes` ADD CONSTRAINT `FK_7add69eb9dff06d1b36ce5fccdf` FOREIGN KEY (`product_id`) REFERENCES `products`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
    //     await queryRunner.query("ALTER TABLE `products` ADD CONSTRAINT `FK_98086f14e190574534d5129cd7c` FOREIGN KEY (`uuid`) REFERENCES `users`(`uuid`) ON DELETE NO ACTION ON UPDATE NO ACTION");
    //     await queryRunner.query("ALTER TABLE `products` ADD CONSTRAINT `FK_1530a6f15d3c79d1b70be98f2be` FOREIGN KEY (`brand_id`) REFERENCES `brand`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
    //     await queryRunner.query("ALTER TABLE `product_videos_categories_category` ADD CONSTRAINT `FK_e0b4b616bf39de996dc29b7054a` FOREIGN KEY (`productVideosId`) REFERENCES `product_videos`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
    //     await queryRunner.query("ALTER TABLE `product_videos_categories_category` ADD CONSTRAINT `FK_778ef644710167120f69eb5571f` FOREIGN KEY (`categoryId`) REFERENCES `category`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
    //     await queryRunner.query("ALTER TABLE `product_videos_subcategories_subcategories` ADD CONSTRAINT `FK_aee71e905a465bccf1d1b50215b` FOREIGN KEY (`productVideosId`) REFERENCES `product_videos`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
    //     await queryRunner.query("ALTER TABLE `product_videos_subcategories_subcategories` ADD CONSTRAINT `FK_e5580fb9f26dda404a495b20199` FOREIGN KEY (`subcategoriesId`) REFERENCES `subcategories`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
    //     await queryRunner.query("ALTER TABLE `users_interests` ADD CONSTRAINT `FK_a84a9353e088300f9be74b22453` FOREIGN KEY (`uuid`) REFERENCES `users`(`uuid`) ON DELETE CASCADE ON UPDATE NO ACTION");
    //     await queryRunner.query("ALTER TABLE `users_interests` ADD CONSTRAINT `FK_70bcbd738b4195c74086caa698c` FOREIGN KEY (`interest_id`) REFERENCES `interests`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
    //     await queryRunner.query("ALTER TABLE `products_categories_category` ADD CONSTRAINT `FK_472c77dfe20a4c6d4258dc8379f` FOREIGN KEY (`productsId`) REFERENCES `products`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
    //     await queryRunner.query("ALTER TABLE `products_categories_category` ADD CONSTRAINT `FK_62254eefb150c9a51119fe1a613` FOREIGN KEY (`categoryId`) REFERENCES `category`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
    //     await queryRunner.query("ALTER TABLE `products_subcategories_subcategories` ADD CONSTRAINT `FK_016da0d1d10bf7436c948a0182d` FOREIGN KEY (`productsId`) REFERENCES `products`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
    //     await queryRunner.query("ALTER TABLE `products_subcategories_subcategories` ADD CONSTRAINT `FK_63446ee0abb6d0decfa7ac24946` FOREIGN KEY (`subcategoriesId`) REFERENCES `subcategories`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
    //     await queryRunner.query("ALTER TABLE `products_subcategories_subcategories` DROP FOREIGN KEY `FK_63446ee0abb6d0decfa7ac24946`");
    //     await queryRunner.query("ALTER TABLE `products_subcategories_subcategories` DROP FOREIGN KEY `FK_016da0d1d10bf7436c948a0182d`");
    //     await queryRunner.query("ALTER TABLE `products_categories_category` DROP FOREIGN KEY `FK_62254eefb150c9a51119fe1a613`");
    //     await queryRunner.query("ALTER TABLE `products_categories_category` DROP FOREIGN KEY `FK_472c77dfe20a4c6d4258dc8379f`");
    //     await queryRunner.query("ALTER TABLE `users_interests` DROP FOREIGN KEY `FK_70bcbd738b4195c74086caa698c`");
    //     await queryRunner.query("ALTER TABLE `users_interests` DROP FOREIGN KEY `FK_a84a9353e088300f9be74b22453`");
    //     await queryRunner.query("ALTER TABLE `product_videos_subcategories_subcategories` DROP FOREIGN KEY `FK_e5580fb9f26dda404a495b20199`");
    //     await queryRunner.query("ALTER TABLE `product_videos_subcategories_subcategories` DROP FOREIGN KEY `FK_aee71e905a465bccf1d1b50215b`");
    //     await queryRunner.query("ALTER TABLE `product_videos_categories_category` DROP FOREIGN KEY `FK_778ef644710167120f69eb5571f`");
    //     await queryRunner.query("ALTER TABLE `product_videos_categories_category` DROP FOREIGN KEY `FK_e0b4b616bf39de996dc29b7054a`");
    //     await queryRunner.query("ALTER TABLE `products` DROP FOREIGN KEY `FK_1530a6f15d3c79d1b70be98f2be`");
    //     await queryRunner.query("ALTER TABLE `products` DROP FOREIGN KEY `FK_98086f14e190574534d5129cd7c`");
    //     await queryRunner.query("ALTER TABLE `product_likes` DROP FOREIGN KEY `FK_7add69eb9dff06d1b36ce5fccdf`");
    //     await queryRunner.query("ALTER TABLE `product_likes` DROP FOREIGN KEY `FK_e7dbd6e2295d469fc765a986f15`");
    //     await queryRunner.query("ALTER TABLE `users` DROP FOREIGN KEY `FK_d98a275f8bc6cd986fcbe2eab01`");
        // await queryRunner.query("ALTER TABLE `services` DROP FOREIGN KEY `FK_421b94f0ef1cdb407654e67c59e`");
    //     await queryRunner.query("ALTER TABLE `user_activities` DROP FOREIGN KEY `FK_a283f37e08edf5e37d38b375eec`");
    //     await queryRunner.query("ALTER TABLE `product_video_likes` DROP FOREIGN KEY `FK_1c2afb95868c0c0329864b303bb`");
    //     await queryRunner.query("ALTER TABLE `product_video_likes` DROP FOREIGN KEY `FK_ee327d2dc279475e612f40e2163`");
    //     await queryRunner.query("ALTER TABLE `product_videos` DROP FOREIGN KEY `FK_ac5dbef0a796bca08eded59df73`");
    //     await queryRunner.query("ALTER TABLE `product_video_meta` DROP FOREIGN KEY `FK_fc9de53de4f59d06b8ec2346f51`");
    //     await queryRunner.query("ALTER TABLE `product_video_comment` DROP FOREIGN KEY `FK_1b40bb3804949aabd9eac604a2b`");
    //     await queryRunner.query("ALTER TABLE `product_video_comment` DROP FOREIGN KEY `FK_25bba93110aa8bd1a0dfefc9821`");
    //     await queryRunner.query("ALTER TABLE `peggs` DROP FOREIGN KEY `FK_b15dc25d7663ee05f6c234679c8`");
    //     await queryRunner.query("ALTER TABLE `peggs` DROP FOREIGN KEY `FK_02056a85e905642f887f5ca99a6`");
    //     await queryRunner.query("ALTER TABLE `shops` DROP FOREIGN KEY `FK_045cb5bc6b83e5d5f99f4a7966c`");
    //     await queryRunner.query("ALTER TABLE `shops` DROP FOREIGN KEY `FK_bb9c758dcc60137e56f6fee72f7`");
    //     await queryRunner.query("ALTER TABLE `promotional_videos` DROP FOREIGN KEY `FK_cad94a0d1cc1263de58b6aa9b76`");
    //     await queryRunner.query("ALTER TABLE `promotional_videos` DROP FOREIGN KEY `FK_201b844b99b0a5777d68581c8ce`");
    //     await queryRunner.query("ALTER TABLE `promotional_videos` DROP FOREIGN KEY `FK_f470cfd5581b2d6970cb5835346`");
    //     await queryRunner.query("ALTER TABLE `subcategories` DROP FOREIGN KEY `FK_f7b015bc580ae5179ba5a4f42ec`");
    //     await queryRunner.query("ALTER TABLE `promotional_likes` DROP FOREIGN KEY `FK_5c28d36e7ae9177124dfd56134b`");
    //     await queryRunner.query("ALTER TABLE `promotional_likes` DROP FOREIGN KEY `FK_3b40b6056b45040706bb9e09f00`");
    //     await queryRunner.query("ALTER TABLE `promotional_comments` DROP FOREIGN KEY `FK_f5dd43a69913c2bfae925f4bcea`");
    //     await queryRunner.query("ALTER TABLE `promotional_comments` DROP FOREIGN KEY `FK_8d2bd18dfbc56788fb3eb9f6460`");
    //     await queryRunner.query("ALTER TABLE `generated_video_tags` DROP FOREIGN KEY `FK_009993ac242f5343e6b9a2b5c0c`");
    //     await queryRunner.query("ALTER TABLE `generated_video_tags` DROP FOREIGN KEY `FK_3d0fba6255dd2335034e78dd25a`");
    //     await queryRunner.query("ALTER TABLE `carts` DROP FOREIGN KEY `FK_2ec1c94a977b940d85a4f498aea`");
    //     await queryRunner.query("ALTER TABLE `carts` DROP FOREIGN KEY `FK_7d0e145ebd287c1565f15114a18`");
    //     await queryRunner.query("ALTER TABLE `carts` DROP FOREIGN KEY `FK_ab18eaf5265160d3dc8d70d9227`");
    //     await queryRunner.query("ALTER TABLE `product_comment` DROP FOREIGN KEY `FK_082d130dfa3d29fc2dd46141936`");
    //     await queryRunner.query("ALTER TABLE `product_comment` DROP FOREIGN KEY `FK_add4013879e5a3bd0d59b9cba2e`");
    //     await queryRunner.query("ALTER TABLE `order` DROP FOREIGN KEY `FK_ba94d4066f76b66d3fe0b94c283`");
    //     await queryRunner.query("ALTER TABLE `order_item` DROP FOREIGN KEY `FK_5e17c017aa3f5164cb2da5b1c6b`");
    //     await queryRunner.query("ALTER TABLE `order_item` DROP FOREIGN KEY `FK_e9674a6053adbaa1057848cddfa`");
    //     await queryRunner.query("ALTER TABLE `product_picture` DROP FOREIGN KEY `FK_d4fc8e8168628ebd69131ff21dd`");
    //     await queryRunner.query("ALTER TABLE `otp_verifies` DROP COLUMN `updated_at`");
    //     await queryRunner.query("ALTER TABLE `otp_verifies` ADD `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
    //     await queryRunner.query("ALTER TABLE `otp_verifies` DROP COLUMN `created_at`");
    //     await queryRunner.query("ALTER TABLE `otp_verifies` ADD `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
    //     await queryRunner.query("ALTER TABLE `otp_verifies` DROP INDEX `IDX_f71c5348cfeceeade91fd6231e`");
    //     await queryRunner.query("ALTER TABLE `otp_verifies` DROP COLUMN `email`");
    //     await queryRunner.query("ALTER TABLE `otp_verifies` ADD `email` varchar(191) NULL");
    //     await queryRunner.query("CREATE UNIQUE INDEX `IDX_f71c5348cfeceeade91fd6231e` ON `otp_verifies` (`email`)");
    //     await queryRunner.query("ALTER TABLE `products` DROP COLUMN `updated_at`");
    //     await queryRunner.query("ALTER TABLE `products` ADD `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
    //     await queryRunner.query("ALTER TABLE `products` DROP COLUMN `created_at`");
    //     await queryRunner.query("ALTER TABLE `products` ADD `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
    //     await queryRunner.query("ALTER TABLE `products` CHANGE `product_status` `product_status` int NULL DEFAULT '1'");
    //     await queryRunner.query("ALTER TABLE `products` CHANGE `status` `status` int NULL DEFAULT '1'");
    //     await queryRunner.query("ALTER TABLE `products` DROP COLUMN `brand_id`");
    //     await queryRunner.query("ALTER TABLE `products` ADD `brand_id` varchar(191) NULL");
    //     await queryRunner.query("ALTER TABLE `products` CHANGE `description` `description` longtext NULL");
    //     await queryRunner.query("ALTER TABLE `products` CHANGE `product_processed_meta` `product_processed_meta` longtext NULL");
    //     await queryRunner.query("ALTER TABLE `products` CHANGE `product_processed_status` `product_processed_status` int NULL");
    //     await queryRunner.query("ALTER TABLE `products` DROP COLUMN `price`");
    //     await queryRunner.query("ALTER TABLE `products` ADD `price` decimal NULL");
    //     await queryRunner.query("ALTER TABLE `products` DROP COLUMN `thumbnail`");
    //     await queryRunner.query("ALTER TABLE `products` ADD `thumbnail` varchar(191) NULL");
    //     await queryRunner.query("ALTER TABLE `products` DROP COLUMN `slug`");
    //     await queryRunner.query("ALTER TABLE `products` ADD `slug` varchar(191) NULL");
    //     await queryRunner.query("ALTER TABLE `products` DROP COLUMN `name`");
    //     await queryRunner.query("ALTER TABLE `products` ADD `name` varchar(191) NULL");
    //     await queryRunner.query("ALTER TABLE `product_likes` DROP COLUMN `product_id`");
    //     await queryRunner.query("ALTER TABLE `product_likes` ADD `product_id` varchar(191) NOT NULL");
    //     await queryRunner.query("ALTER TABLE `product_likes` DROP COLUMN `updated_at`");
    //     await queryRunner.query("ALTER TABLE `product_likes` ADD `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
    //     await queryRunner.query("ALTER TABLE `product_likes` DROP COLUMN `created_at`");
    //     await queryRunner.query("ALTER TABLE `product_likes` ADD `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
    //     await queryRunner.query("ALTER TABLE `product_likes` CHANGE `likes` `likes` int NOT NULL DEFAULT '0'");
    //     await queryRunner.query("ALTER TABLE `product_likes` ADD CONSTRAINT `FK_7add69eb9dff06d1b36ce5fccdf` FOREIGN KEY (`product_id`) REFERENCES `products`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
    //     await queryRunner.query("ALTER TABLE `users` DROP COLUMN `updated_at`");
    //     await queryRunner.query("ALTER TABLE `users` ADD `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
    //     await queryRunner.query("ALTER TABLE `users` DROP COLUMN `created_at`");
    //     await queryRunner.query("ALTER TABLE `users` ADD `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
    //     await queryRunner.query("ALTER TABLE `users` DROP COLUMN `remember_token`");
    //     await queryRunner.query("ALTER TABLE `users` ADD `remember_token` varchar(191) NULL");
    //     await queryRunner.query("ALTER TABLE `users` DROP COLUMN `is_banned`");
    //     await queryRunner.query("ALTER TABLE `users` ADD `is_banned` tinyint NOT NULL DEFAULT '0'");
    //     await queryRunner.query("ALTER TABLE `users` DROP COLUMN `is_active`");
    //     await queryRunner.query("ALTER TABLE `users` ADD `is_active` tinyint NOT NULL DEFAULT '0'");
    //     await queryRunner.query("ALTER TABLE `users` DROP COLUMN `email_verified_at`");
    //     await queryRunner.query("ALTER TABLE `users` ADD `email_verified_at` timestamp NULL");
    //     await queryRunner.query("ALTER TABLE `users` DROP COLUMN `password`");
    //     await queryRunner.query("ALTER TABLE `users` ADD `password` varchar(191) NOT NULL");
    //     await queryRunner.query("ALTER TABLE `users` DROP COLUMN `country_code`");
    //     await queryRunner.query("ALTER TABLE `users` ADD `country_code` int NULL");
    //     await queryRunner.query("ALTER TABLE `users` DROP COLUMN `country_id`");
    //     await queryRunner.query("ALTER TABLE `users` ADD `country_id` varchar(191) NULL");
    //     await queryRunner.query("ALTER TABLE `users` DROP COLUMN `device_type`");
    //     await queryRunner.query("ALTER TABLE `users` ADD `device_type` varchar(191) NULL");
    //     await queryRunner.query("ALTER TABLE `users` DROP COLUMN `device_id`");
    //     await queryRunner.query("ALTER TABLE `users` ADD `device_id` varchar(191) NULL");
    //     await queryRunner.query("ALTER TABLE `users` DROP COLUMN `longitude`");
    //     await queryRunner.query("ALTER TABLE `users` ADD `longitude` varchar(191) NULL");
    //     await queryRunner.query("ALTER TABLE `users` DROP COLUMN `latitude`");
    //     await queryRunner.query("ALTER TABLE `users` ADD `latitude` varchar(191) NULL");
    //     await queryRunner.query("ALTER TABLE `users` CHANGE `gender` `gender` enum ('Male', 'Female', 'Others') NULL");
    //     await queryRunner.query("ALTER TABLE `users` DROP COLUMN `picture`");
    //     await queryRunner.query("ALTER TABLE `users` ADD `picture` varchar(191) NULL");
    //     await queryRunner.query("ALTER TABLE `users` DROP COLUMN `phone`");
    //     await queryRunner.query("ALTER TABLE `users` ADD `phone` varchar(191) NOT NULL");
    //     await queryRunner.query("ALTER TABLE `users` DROP INDEX `IDX_97672ac88f789774dd47f7c8be`");
    //     await queryRunner.query("ALTER TABLE `users` DROP COLUMN `email`");
    //     await queryRunner.query("ALTER TABLE `users` ADD `email` varchar(191) NOT NULL");
    //     await queryRunner.query("CREATE UNIQUE INDEX `IDX_97672ac88f789774dd47f7c8be` ON `users` (`email`)");
    //     await queryRunner.query("ALTER TABLE `users` DROP INDEX `IDX_fe0bb3f6520ee0469504521e71`");
    //     await queryRunner.query("ALTER TABLE `users` DROP COLUMN `username`");
    //     await queryRunner.query("ALTER TABLE `users` ADD `username` varchar(191) NOT NULL");
    //     await queryRunner.query("CREATE UNIQUE INDEX `IDX_fe0bb3f6520ee0469504521e71` ON `users` (`username`)");
    //     await queryRunner.query("ALTER TABLE `users` DROP COLUMN `id`");
    //     await queryRunner.query("ALTER TABLE `users` ADD `id` varchar(36) NOT NULL");
    //     await queryRunner.query("ALTER TABLE `users` DROP PRIMARY KEY");
    //     await queryRunner.query("ALTER TABLE `users` ADD PRIMARY KEY (`id`, `uuid`)");
        await queryRunner.query("ALTER TABLE `services` CHANGE `is_deleted` `is_deleted` tinyint NOT NULL");
    //     await queryRunner.query("ALTER TABLE `user_activities` DROP COLUMN `updated_at`");
    //     await queryRunner.query("ALTER TABLE `user_activities` ADD `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
    //     await queryRunner.query("ALTER TABLE `user_activities` DROP COLUMN `created_at`");
    //     await queryRunner.query("ALTER TABLE `user_activities` ADD `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
    //     await queryRunner.query("ALTER TABLE `user_activities` DROP COLUMN `type`");
    //     await queryRunner.query("ALTER TABLE `user_activities` ADD `type` enum ('web', 'mobile') NULL");
    //     await queryRunner.query("ALTER TABLE `user_activities` DROP COLUMN `id`");
    //     await queryRunner.query("ALTER TABLE `user_activities` ADD `id` varchar(36) NOT NULL");
    //     await queryRunner.query("ALTER TABLE `user_activities` ADD PRIMARY KEY (`id`)");
    //     await queryRunner.query("ALTER TABLE `product_videos` DROP COLUMN `updated_at`");
    //     await queryRunner.query("ALTER TABLE `product_videos` ADD `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
    //     await queryRunner.query("ALTER TABLE `product_videos` DROP COLUMN `created_at`");
    //     await queryRunner.query("ALTER TABLE `product_videos` ADD `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
    //     await queryRunner.query("ALTER TABLE `product_videos` DROP COLUMN `mp4_url`");
    //     await queryRunner.query("ALTER TABLE `product_videos` ADD `mp4_url` varchar(191) NOT NULL");
    //     await queryRunner.query("ALTER TABLE `product_videos` DROP COLUMN `json`");
    //     await queryRunner.query("ALTER TABLE `product_videos` ADD `json` varchar(191) NOT NULL");
    //     await queryRunner.query("ALTER TABLE `product_videos` DROP COLUMN `thumbnail`");
    //     await queryRunner.query("ALTER TABLE `product_videos` ADD `thumbnail` varchar(191) NOT NULL");
    //     await queryRunner.query("ALTER TABLE `product_videos` DROP COLUMN `description`");
    //     await queryRunner.query("ALTER TABLE `product_videos` ADD `description` varchar(191) NOT NULL");
    //     await queryRunner.query("ALTER TABLE `product_videos` DROP COLUMN `title`");
    //     await queryRunner.query("ALTER TABLE `product_videos` ADD `title` varchar(191) NOT NULL");
    //     await queryRunner.query("ALTER TABLE `peggs` DROP COLUMN `centroid`");
    //     await queryRunner.query("ALTER TABLE `peggs` ADD `centroid` varchar(191) NOT NULL");
    //     await queryRunner.query("ALTER TABLE `peggs` DROP COLUMN `millisecond`");
    //     await queryRunner.query("ALTER TABLE `peggs` ADD `millisecond` varchar(191) NOT NULL");
    //     await queryRunner.query("ALTER TABLE `peggs` DROP COLUMN `boundingBoxLeft`");
    //     await queryRunner.query("ALTER TABLE `peggs` ADD `boundingBoxLeft` varchar(191) NOT NULL");
    //     await queryRunner.query("ALTER TABLE `peggs` DROP COLUMN `boundingBoxTop`");
    //     await queryRunner.query("ALTER TABLE `peggs` ADD `boundingBoxTop` varchar(191) NOT NULL");
    //     await queryRunner.query("ALTER TABLE `peggs` DROP COLUMN `boundingBoxWidth`");
    //     await queryRunner.query("ALTER TABLE `peggs` ADD `boundingBoxWidth` varchar(191) NOT NULL");
    //     await queryRunner.query("ALTER TABLE `peggs` DROP COLUMN `boundingBoxHeight`");
    //     await queryRunner.query("ALTER TABLE `peggs` ADD `boundingBoxHeight` varchar(191) NOT NULL");
    //     await queryRunner.query("ALTER TABLE `peggs` DROP COLUMN `confidence`");
    //     await queryRunner.query("ALTER TABLE `peggs` ADD `confidence` varchar(191) NOT NULL");
    //     await queryRunner.query("ALTER TABLE `peggs` DROP COLUMN `label`");
    //     await queryRunner.query("ALTER TABLE `peggs` ADD `label` varchar(191) NOT NULL");
    //     await queryRunner.query("ALTER TABLE `peggs` DROP COLUMN `product_id`");
    //     await queryRunner.query("ALTER TABLE `peggs` ADD `product_id` varchar(191) NULL");
    //     await queryRunner.query("ALTER TABLE `peggs` DROP COLUMN `video_id`");
    //     await queryRunner.query("ALTER TABLE `peggs` ADD `video_id` varchar(191) NULL");
    //     await queryRunner.query("ALTER TABLE `peggs` ADD CONSTRAINT `FK_02056a85e905642f887f5ca99a6` FOREIGN KEY (`video_id`) REFERENCES `product_videos`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
    //     await queryRunner.query("ALTER TABLE `shops` CHANGE `user_id` `user_id` varchar(191) NULL");
    //     await queryRunner.query("ALTER TABLE `shops` ADD CONSTRAINT `FK_bb9c758dcc60137e56f6fee72f7` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
    //     await queryRunner.query("ALTER TABLE `promotional_likes` DROP COLUMN `updated_at`");
    //     await queryRunner.query("ALTER TABLE `promotional_likes` ADD `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
    //     await queryRunner.query("ALTER TABLE `promotional_likes` DROP COLUMN `created_at`");
    //     await queryRunner.query("ALTER TABLE `promotional_likes` ADD `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
    //     await queryRunner.query("ALTER TABLE `promotional_likes` DROP COLUMN `prod_vid_id`");
    //     await queryRunner.query("ALTER TABLE `promotional_likes` ADD `prod_vid_id` varchar(191) NOT NULL");
    //     await queryRunner.query("ALTER TABLE `promotional_likes` DROP COLUMN `user_id`");
    //     await queryRunner.query("ALTER TABLE `promotional_likes` ADD `user_id` varchar(191) NOT NULL");
    //     await queryRunner.query("ALTER TABLE `promotional_likes` DROP COLUMN `id`");
    //     await queryRunner.query("ALTER TABLE `promotional_likes` ADD `id` varchar(36) NOT NULL");
    //     await queryRunner.query("ALTER TABLE `promotional_likes` ADD PRIMARY KEY (`id`)");
    //     await queryRunner.query("ALTER TABLE `promotional_comments` DROP COLUMN `updated_at`");
    //     await queryRunner.query("ALTER TABLE `promotional_comments` ADD `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
    //     await queryRunner.query("ALTER TABLE `promotional_comments` DROP COLUMN `created_at`");
    //     await queryRunner.query("ALTER TABLE `promotional_comments` ADD `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
    //     await queryRunner.query("ALTER TABLE `promotional_comments` DROP COLUMN `pro_vid_id`");
    //     await queryRunner.query("ALTER TABLE `promotional_comments` ADD `pro_vid_id` varchar(191) NOT NULL");
    //     await queryRunner.query("ALTER TABLE `promotional_comments` DROP COLUMN `user_id`");
    //     await queryRunner.query("ALTER TABLE `promotional_comments` ADD `user_id` varchar(191) NOT NULL");
    //     await queryRunner.query("ALTER TABLE `promotional_comments` DROP COLUMN `id`");
    //     await queryRunner.query("ALTER TABLE `promotional_comments` ADD `id` varchar(36) NOT NULL");
    //     await queryRunner.query("ALTER TABLE `promotional_comments` ADD PRIMARY KEY (`id`)");
    //     await queryRunner.query("ALTER TABLE `generated_video_tags` DROP COLUMN `updated_at`");
    //     await queryRunner.query("ALTER TABLE `generated_video_tags` ADD `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
    //     await queryRunner.query("ALTER TABLE `generated_video_tags` DROP COLUMN `created_at`");
    //     await queryRunner.query("ALTER TABLE `generated_video_tags` ADD `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
    //     await queryRunner.query("ALTER TABLE `generated_video_tags` DROP COLUMN `y`");
    //     await queryRunner.query("ALTER TABLE `generated_video_tags` ADD `y` varchar(191) NOT NULL");
    //     await queryRunner.query("ALTER TABLE `generated_video_tags` DROP COLUMN `x`");
    //     await queryRunner.query("ALTER TABLE `generated_video_tags` ADD `x` varchar(191) NOT NULL");
    //     await queryRunner.query("ALTER TABLE `generated_video_tags` DROP COLUMN `product_id`");
    //     await queryRunner.query("ALTER TABLE `generated_video_tags` ADD `product_id` varchar(191) NOT NULL");
    //     await queryRunner.query("ALTER TABLE `generated_video_tags` DROP COLUMN `price`");
    //     await queryRunner.query("ALTER TABLE `generated_video_tags` ADD `price` decimal NOT NULL");
    //     await queryRunner.query("ALTER TABLE `generated_video_tags` DROP COLUMN `label`");
    //     await queryRunner.query("ALTER TABLE `generated_video_tags` ADD `label` varchar(191) NOT NULL");
    //     await queryRunner.query("ALTER TABLE `generated_video_tags` DROP COLUMN `video_id`");
    //     await queryRunner.query("ALTER TABLE `generated_video_tags` ADD `video_id` varchar(191) NOT NULL");
    //     await queryRunner.query("ALTER TABLE `carts` DROP COLUMN `updated_at`");
    //     await queryRunner.query("ALTER TABLE `carts` ADD `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
    //     await queryRunner.query("ALTER TABLE `carts` DROP COLUMN `created_at`");
    //     await queryRunner.query("ALTER TABLE `carts` ADD `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
    //     await queryRunner.query("ALTER TABLE `carts` DROP COLUMN `color_id`");
    //     await queryRunner.query("ALTER TABLE `carts` ADD `color_id` varchar(191) NULL");
    //     await queryRunner.query("ALTER TABLE `carts` CHANGE `quantity` `quantity` int NULL");
    //     await queryRunner.query("ALTER TABLE `carts` DROP COLUMN `weight`");
    //     await queryRunner.query("ALTER TABLE `carts` ADD `weight` varchar(191) NULL");
    //     await queryRunner.query("ALTER TABLE `carts` DROP COLUMN `size`");
    //     await queryRunner.query("ALTER TABLE `carts` ADD `size` varchar(191) NULL");
    //     await queryRunner.query("ALTER TABLE `carts` CHANGE `status` `status` int NULL DEFAULT '0'");
    //     await queryRunner.query("ALTER TABLE `carts` DROP COLUMN `product_id`");
    //     await queryRunner.query("ALTER TABLE `carts` ADD `product_id` varchar(191) NULL");
    //     await queryRunner.query("ALTER TABLE `carts` DROP COLUMN `user_id`");
    //     await queryRunner.query("ALTER TABLE `carts` ADD `user_id` varchar(191) NULL");
    //     await queryRunner.query("ALTER TABLE `carts` ADD CONSTRAINT `FK_2ec1c94a977b940d85a4f498aea` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
    //     await queryRunner.query("ALTER TABLE `colors` DROP COLUMN `updated_at`");
    //     await queryRunner.query("ALTER TABLE `colors` ADD `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
    //     await queryRunner.query("ALTER TABLE `colors` DROP COLUMN `created_at`");
    //     await queryRunner.query("ALTER TABLE `colors` ADD `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
    //     await queryRunner.query("ALTER TABLE `colors` DROP COLUMN `code`");
    //     await queryRunner.query("ALTER TABLE `colors` ADD `code` varchar(191) NOT NULL");
    //     await queryRunner.query("ALTER TABLE `colors` DROP COLUMN `name`");
    //     await queryRunner.query("ALTER TABLE `colors` ADD `name` varchar(191) NOT NULL");
    //     await queryRunner.query("ALTER TABLE `interests` DROP COLUMN `updated_at`");
    //     await queryRunner.query("ALTER TABLE `interests` ADD `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
    //     await queryRunner.query("ALTER TABLE `interests` DROP COLUMN `created_at`");
    //     await queryRunner.query("ALTER TABLE `interests` ADD `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
    //     await queryRunner.query("ALTER TABLE `interests` DROP COLUMN `picture`");
    //     await queryRunner.query("ALTER TABLE `interests` ADD `picture` varchar(191) NOT NULL");
    //     await queryRunner.query("ALTER TABLE `interests` DROP COLUMN `video`");
    //     await queryRunner.query("ALTER TABLE `interests` ADD `video` varchar(191) NOT NULL");
    //     await queryRunner.query("ALTER TABLE `interests` DROP INDEX `IDX_616348777087f88bb8cb743e60`");
    //     await queryRunner.query("ALTER TABLE `interests` DROP COLUMN `name`");
    //     await queryRunner.query("ALTER TABLE `interests` ADD `name` varchar(191) NOT NULL");
    //     await queryRunner.query("CREATE UNIQUE INDEX `IDX_616348777087f88bb8cb743e60` ON `interests` (`name`)");
    //     await queryRunner.query("ALTER TABLE `otp_verifies` DROP COLUMN `uuid`");
    //     await queryRunner.query("ALTER TABLE `products` DROP COLUMN `weight`");
    //     await queryRunner.query("ALTER TABLE `products` DROP COLUMN `size`");
    //     await queryRunner.query("ALTER TABLE `products` DROP COLUMN `color`");
        // await queryRunner.query("ALTER TABLE `products` DROP COLUMN `uuid`");
        // await queryRunner.query("ALTER TABLE `product_likes` DROP COLUMN `uuid`");
        // await queryRunner.query("ALTER TABLE `users` DROP COLUMN `account_type`");
        // await queryRunner.query("ALTER TABLE `users` DROP PRIMARY KEY");
        // await queryRunner.query("ALTER TABLE `users` ADD PRIMARY KEY (`id`)");
        // await queryRunner.query("ALTER TABLE `users` DROP COLUMN `uuid`");
        // await queryRunner.query("ALTER TABLE `product_videos` DROP COLUMN `uuid`");
        // await queryRunner.query("ALTER TABLE `activity_types` DROP COLUMN `id`");
        // await queryRunner.query("ALTER TABLE `otp_verifies` ADD `status` int NOT NULL DEFAULT '0'");
        // await queryRunner.query("ALTER TABLE `otp_verifies` ADD `user_id` varchar(191) NOT NULL");
        // await queryRunner.query("ALTER TABLE `products` ADD `availability` int NULL DEFAULT '1'");
        // await queryRunner.query("ALTER TABLE `products` ADD `sub_category_id` varchar(36) NULL");
        // await queryRunner.query("ALTER TABLE `products` ADD `sub_categories_id` varchar(191) NULL");
        // await queryRunner.query("ALTER TABLE `products` ADD `category_id` varchar(191) NULL");
        // await queryRunner.query("ALTER TABLE `products` ADD `products_status` int NULL DEFAULT '0'");
        // await queryRunner.query("ALTER TABLE `products` ADD `is_deleted` tinyint NULL");
        // await queryRunner.query("ALTER TABLE `products` ADD `color_id` varchar(191) NULL");
        // await queryRunner.query("ALTER TABLE `products` ADD `user_id` varchar(191) NULL");
        // await queryRunner.query("ALTER TABLE `product_likes` ADD `status` int NOT NULL DEFAULT '0'");
        // await queryRunner.query("ALTER TABLE `product_likes` ADD `user_id` varchar(191) NOT NULL");
        // await queryRunner.query("ALTER TABLE `users` ADD `date_deleted` datetime NULL");
        // await queryRunner.query("ALTER TABLE `users` ADD `is_deleted` tinyint NOT NULL DEFAULT '0'");
        // await queryRunner.query("ALTER TABLE `users` ADD `account_type_id` int NOT NULL DEFAULT '1'");
        // await queryRunner.query("ALTER TABLE `users` ADD `is_verified` int NOT NULL DEFAULT '0'");
        // await queryRunner.query("ALTER TABLE `users` ADD `address` longtext NULL");
        // await queryRunner.query("ALTER TABLE `user_activities` ADD `is_deleted` tinyint NOT NULL");
        // await queryRunner.query("ALTER TABLE `product_videos` ADD `status` int NOT NULL DEFAULT '0'");
        // await queryRunner.query("ALTER TABLE `product_videos` ADD `is_deleted` tinyint NOT NULL");
        // await queryRunner.query("ALTER TABLE `product_videos` ADD `product_id` varchar(191) NOT NULL");
        // await queryRunner.query("ALTER TABLE `product_videos` ADD `user_id` varchar(191) NOT NULL");
        // await queryRunner.query("ALTER TABLE `peggs` ADD `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        // await queryRunner.query("ALTER TABLE `peggs` ADD `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        // await queryRunner.query("ALTER TABLE `shops` ADD `logistic_id` varchar(191) NULL");
        // await queryRunner.query("ALTER TABLE `promotional_likes` ADD `status` int NOT NULL DEFAULT '0'");
        // await queryRunner.query("ALTER TABLE `promotional_likes` ADD `is_deleted` tinyint NOT NULL");
        // await queryRunner.query("ALTER TABLE `promotional_comments` ADD `status` int NOT NULL DEFAULT '0'");
        // await queryRunner.query("ALTER TABLE `promotional_comments` ADD `is_deleted` tinyint NOT NULL");
        // await queryRunner.query("ALTER TABLE `carts` ADD `is_deleted` tinyint NULL DEFAULT '0'");
        // await queryRunner.query("ALTER TABLE `colors` ADD `is_deleted` tinyint NOT NULL");
        // await queryRunner.query("ALTER TABLE `interests` ADD `is_deleted` tinyint NOT NULL");
        // await queryRunner.query("ALTER TABLE `interests` ADD `slug` varchar(191) NOT NULL");
        // await queryRunner.query("DROP INDEX `IDX_63446ee0abb6d0decfa7ac2494` ON `products_subcategories_subcategories`");
        // await queryRunner.query("DROP INDEX `IDX_016da0d1d10bf7436c948a0182` ON `products_subcategories_subcategories`");
        // await queryRunner.query("DROP TABLE `products_subcategories_subcategories`");
        // await queryRunner.query("DROP INDEX `IDX_62254eefb150c9a51119fe1a61` ON `products_categories_category`");
        // await queryRunner.query("DROP INDEX `IDX_472c77dfe20a4c6d4258dc8379` ON `products_categories_category`");
        // await queryRunner.query("DROP TABLE `products_categories_category`");
        // await queryRunner.query("DROP INDEX `IDX_70bcbd738b4195c74086caa698` ON `users_interests`");
        // await queryRunner.query("DROP INDEX `IDX_a84a9353e088300f9be74b2245` ON `users_interests`");
        // await queryRunner.query("DROP TABLE `users_interests`");
        // await queryRunner.query("DROP INDEX `IDX_e5580fb9f26dda404a495b2019` ON `product_videos_subcategories_subcategories`");
        // await queryRunner.query("DROP INDEX `IDX_aee71e905a465bccf1d1b50215` ON `product_videos_subcategories_subcategories`");
        // await queryRunner.query("DROP TABLE `product_videos_subcategories_subcategories`");
        // await queryRunner.query("DROP INDEX `IDX_778ef644710167120f69eb5571` ON `product_videos_categories_category`");
        // await queryRunner.query("DROP INDEX `IDX_e0b4b616bf39de996dc29b7054` ON `product_videos_categories_category`");
        // await queryRunner.query("DROP TABLE `product_videos_categories_category`");
        // await queryRunner.query("DROP TABLE `pegg`");
        // await queryRunner.query("DROP TABLE `brand`");
        // await queryRunner.query("DROP TABLE `product_video_likes`");
        // await queryRunner.query("DROP TABLE `product_video_comment`");
        // await queryRunner.query("DROP INDEX `IDX_23c05c292c439d77b0de816b50` ON `category`");
        // await queryRunner.query("DROP TABLE `category`");
        // await queryRunner.query("DROP TABLE `promotional_videos`");
        // await queryRunner.query("DROP TABLE `subcategories`");
        // await queryRunner.query("DROP TABLE `product_comment`");
        // await queryRunner.query("DROP INDEX `IDX_a9a66098c2fb758dff713f8d83` ON `token`");
        // await queryRunner.query("DROP TABLE `token`");
        // await queryRunner.query("DROP TABLE `order`");
        // await queryRunner.query("DROP TABLE `order_item`");
        // await queryRunner.query("DROP TABLE `product_picture`");
        // await queryRunner.query("CREATE UNIQUE INDEX `REL_4bee29aa25fc3adccf1653731d` ON `product_videos` (`product_id`)");
        // await queryRunner.query("ALTER TABLE `products` ADD CONSTRAINT `FK_9a5f6868c96e0069e699f33e124` FOREIGN KEY (`category_id`) REFERENCES `categories`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        // await queryRunner.query("ALTER TABLE `products` ADD CONSTRAINT `FK_3fffb0be83ac483af3a55f41170` FOREIGN KEY (`sub_category_id`) REFERENCES `sub_categories`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        // await queryRunner.query("ALTER TABLE `products` ADD CONSTRAINT `FK_176b502c5ebd6e72cafbd9d6f70` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        // await queryRunner.query("ALTER TABLE `products` ADD CONSTRAINT `FK_1530a6f15d3c79d1b70be98f2be` FOREIGN KEY (`brand_id`) REFERENCES `brands`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        // await queryRunner.query("ALTER TABLE `product_likes` ADD CONSTRAINT `FK_4e72406feff8da9492589672947` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        // await queryRunner.query("ALTER TABLE `users` ADD CONSTRAINT `FK_d98a275f8bc6cd986fcbe2eab01` FOREIGN KEY (`tokenId`) REFERENCES `tokens`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        // await queryRunner.query("ALTER TABLE `user_activities` ADD CONSTRAINT `FK_a283f37e08edf5e37d38b375eec` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        // await queryRunner.query("ALTER TABLE `product_videos` ADD CONSTRAINT `FK_4bee29aa25fc3adccf1653731df` FOREIGN KEY (`product_id`) REFERENCES `products`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        // await queryRunner.query("ALTER TABLE `product_videos` ADD CONSTRAINT `FK_14c0e41e47390047c5a9c8b3cb5` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        // await queryRunner.query("ALTER TABLE `peggs` ADD CONSTRAINT `FK_b15dc25d7663ee05f6c234679c8` FOREIGN KEY (`product_id`) REFERENCES `products`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        // await queryRunner.query("ALTER TABLE `shops` ADD CONSTRAINT `FK_045cb5bc6b83e5d5f99f4a7966c` FOREIGN KEY (`category_id`) REFERENCES `categories`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        // await queryRunner.query("ALTER TABLE `promotional_likes` ADD CONSTRAINT `FK_5c28d36e7ae9177124dfd56134b` FOREIGN KEY (`prod_vid_id`) REFERENCES `promotion_videos`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        // await queryRunner.query("ALTER TABLE `promotional_likes` ADD CONSTRAINT `FK_3b40b6056b45040706bb9e09f00` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        // await queryRunner.query("ALTER TABLE `promotional_comments` ADD CONSTRAINT `FK_f5dd43a69913c2bfae925f4bcea` FOREIGN KEY (`pro_vid_id`) REFERENCES `promotion_videos`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        // await queryRunner.query("ALTER TABLE `promotional_comments` ADD CONSTRAINT `FK_8d2bd18dfbc56788fb3eb9f6460` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        // await queryRunner.query("ALTER TABLE `generated_video_tags` ADD CONSTRAINT `FK_009993ac242f5343e6b9a2b5c0c` FOREIGN KEY (`product_id`) REFERENCES `products`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        // await queryRunner.query("ALTER TABLE `generated_video_tags` ADD CONSTRAINT `FK_3d0fba6255dd2335034e78dd25a` FOREIGN KEY (`video_id`) REFERENCES `promotion_videos`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        // await queryRunner.query("ALTER TABLE `carts` ADD CONSTRAINT `FK_ab18eaf5265160d3dc8d70d9227` FOREIGN KEY (`color_id`) REFERENCES `colors`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        // await queryRunner.query("ALTER TABLE `carts` ADD CONSTRAINT `FK_7d0e145ebd287c1565f15114a18` FOREIGN KEY (`product_id`) REFERENCES `products`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
    }

}
